project:
  type: book
  output-dir: docs
book:
  title: "Remote sensing Learning diary"
  author: "Qi Sui"
  date: "2023/1/19"
  chapters:
    - index.qmd
    - intro.qmd
    - W1.qmd
    - W2.qmd
    - W3.qmd
    - W4.qmd
    - W5.qmd
    - W6.qmd
    - W7.qmd
    - W8.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

